### ISSUE TITLE
panic with oidc authentication

### ISSUE THREAD

**Issue by flanaras** [isaaguilar/terraform-operator-cli#5]
Hello,

running `tfo show` or `tfo help` makes the cli exit with the following error and stack trace:

```
panic: no Auth Provider found for name "oidc"

goroutine 1 [running]:
github.com/isaaguilar/terraform-operator-cli/cmd.newSession()
	/Users/isa/git/terraform-operator-cli/cmd/root_cmd.go:76 +0x235
github.com/spf13/cobra.(*Command).preRun(0x2425ee0)
	/Users/isa/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:886 +0x42
github.com/spf13/cobra.(*Command).execute(0x2425ee0, {0x24699c8, 0x0, 0x0})
	/Users/isa/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:822 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x24259e0)
	/Users/isa/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/isa/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/isaaguilar/terraform-operator-cli/cmd.Execute(...)
	/Users/isa/git/terraform-operator-cli/cmd/root_cmd.go:399
main.main()
	/Users/isa/git/terraform-operator-cli/main.go:10 +0x53
```

This is with tfo version 1.1.2, and authentication via oidc.

**Comment by isaaguilar** [comment]
Hi @flanaras ! Thanks for the issue. I found this on gh https://github.com/kubernetes/client-go/issues/345, which seems pretty relevant. I would try and implement it, but for me it's a shot in the dark because I don't have this setup.

**Comment by flanaras** [comment]
Hi @isaaguilar, thanks for the pointer.
It looks like a simple fix. I could give it a shot. Perhaps I have some time to work on it next week.
